name: Reset Ratings

on:
  workflow_dispatch:
  schedule:
    - cron: '55 5 * * *'

jobs:
  reset-ratings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          cd client
          npm install
      - name: Run Reset Ratings
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        run: |
          npm run build
          node dist/ResetRatings.ts
        working-directory: ./client
        shell: bash
      - name: Setup Firebase
        uses: w9jds/firebase-action@v11.24.1
        with:
          firebase-version: '9.6.1'
          config: ${{ secrets.FIREBASE_CONFIG }}
          service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
